"""Change chat_id to BigInteger

Revision ID: 432fc50ac414
Revises: 73c25ec11e2f
Create Date: 2026-09-15 05:57:04.908647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '432fc50ac414'
down_revision: Union[str, Sequence[str], None] = '73c25ec11e2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_botsentmessage_created_at'), table_name='botsentmessage')
    op.drop_index(op.f('ix_botsentmessage_user_id'), table_name='botsentmessage')
    op.drop_table('botsentmessage')
    op.drop_index(op.f('ix_conversationmessage_created_at'), table_name='conversationmessage')
    op.drop_index(op.f('ix_conversationmessage_user_id'), table_name='conversationmessage')
    op.drop_table('conversationmessage')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversationmessage',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tool_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('conversationmessage_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('conversationmessage_pkey'))
    )
    op.create_index(op.f('ix_conversationmessage_user_id'), 'conversationmessage', ['user_id'], unique=False)
    op.create_index(op.f('ix_conversationmessage_created_at'), 'conversationmessage', ['created_at'], unique=False)
    op.create_table('botsentmessage',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('botsentmessage_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('botsentmessage_pkey'))
    )
    op.create_index(op.f('ix_botsentmessage_user_id'), 'botsentmessage', ['user_id'], unique=False)
    op.create_index(op.f('ix_botsentmessage_created_at'), 'botsentmessage', ['created_at'], unique=False)
    # ### end Alembic commands ###
