"""Add botsentmessage and conversationmessage tables

Revision ID: 8980bfa4e2ac
Revises: 432fc50ac414
Create Date: 2026-09-15 06:55:25.441835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8980bfa4e2ac'
down_revision: Union[str, Sequence[str], None] = '432fc50ac414'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('botsentmessage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_botsentmessage_created_at'), 'botsentmessage', ['created_at'], unique=False)
    op.create_index(op.f('ix_botsentmessage_user_id'), 'botsentmessage', ['user_id'], unique=False)
    op.create_table('conversationmessage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversationmessage_created_at'), 'conversationmessage', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversationmessage_user_id'), 'conversationmessage', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversationmessage_user_id'), table_name='conversationmessage')
    op.drop_index(op.f('ix_conversationmessage_created_at'), table_name='conversationmessage')
    op.drop_table('conversationmessage')
    op.drop_index(op.f('ix_botsentmessage_user_id'), table_name='botsentmessage')
    op.drop_index(op.f('ix_botsentmessage_created_at'), table_name='botsentmessage')
    op.drop_table('botsentmessage')
    # ### end Alembic commands ###
